name: Gradle Build and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  gradle-build-and-test:
    runs-on: ubuntu-latest
    container:
      image: gradle:8.3-jdk20-alpine # Matches the GitLab image

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up environment (similar to `before_script`)
      - name: Set Gradle User Home
        run: echo "GRADLE_USER_HOME=$(pwd)/.gradle" >> $GITHUB_ENV

      # Change directory to where `gradlew` is located
      - name: Navigate to Gradle Wrapper Directory
        working-directory: Impatient_java/BookEx
        run: echo "Navigating to $(pwd)"

      # Run tests
      - name: Run Gradle Tests
        working-directory: Impatient_java/BookEx
        run: ./gradlew test

      # Upload test reports
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: |
            Impatient_java/BookEx/app/build/test-results/TEST-*.xml
            Impatient_java/BookEx/app/build/test-results/test/TEST-*.xml

